version: 0.2

env:
  variables:
    IMAGE_NAME: test
    ECR_REPO_URI: 751651548664.dkr.ecr.<region>.amazonaws.com/your-app-name

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region <region>) | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO_URI:$IMAGE_TAG
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_NAME" "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
